language: ruby
rvm:
- 2.3.1
- 2.2.5
- 2.1.10
- jruby
script: LD_LIBRARY_PATH=lib bundle exec rake travis
notifications:
  slack:
    secure: D1gWWsjE9i9XLRM6Bfw2pu3tTPW025iqjhgwE3KNw1QwP2TrehbCwRpjVR4rrnaju9FhYqM0+eT4rFc9g6itBPf2pfN1WziVf/CVJORYTzR9HbLL1rMOaWhEv4x/+Uwu0kxQon9ThnM9w6XjjD1+NoBfGn4Lcgc/OgmUGw1jAvQ=
